version: '3.8'

services:

    vault:
      image: vault:latest
      container_name: vault
      restart: always
      volumes:
        - ./vault/file:/vault/file:rw
        - ./vault/config:/vault/config:rw
        - ./vault/policies:/vault/policies:rw
        - ./vault/data:/vault/data:rw
      ports:
        - 8200:8200
      environment:
        - VAULT_ADDR=http://0.0.0.0:8200
        - VAULT_API_ADDR=http://0.0.0.0:8200
        - VAULT_ADDRESS=http://0.0.0.0:8200
      cap_add:
        - IPC_LOCK
      command: vault server -config=/vault/config/vault.json